language: ruby
rvm:
  - 2.1.0
install:
  - sudo apt-get install texlive texlive-latex-extra
  - gem update --system # maybe fixes timeouts!?
  - gem install squib
script:
  - pdflatex user_error.tex
  - ruby deck.rb
  - cp _output/asset_cards.pdf .
  - cp _output/business_cards.pdf .
  - cp _output/issue_cards.pdf .
addons:
  artifacts:
    paths:
    - user_error.pdf
    - asset_cards.pdf
    - business_cards.pdf
    - issue_cards.pdf
